### ISSUE TITLE
Think of a way to switch couts on and off

### ISSUE THREAD

**Issue by kulagins** [kulagins/tree-scheduler-refactored#14]
The code contains many commented-out cout statements. They are useful during debug, but when we run tests, they need to be suppressed.

We need to find a way to quickly turn them off and on. Previously, this was done by passing "bool quiet" to every function and then doing "if" on it. This cluttered the code immensely (now it is cluttered, too, though).
One possible solution:

- create a global quiet variable
- create a static function print that looks is global quiet is set and then prints/doesn't print
- substitute all couts through this print. 
 
Advantages: achieves the quick turning on/off of the comments, code is less cluttered than with if statements
Disadvantages: still clutters the code

Any other solutions are very welcome

**Comment by kulagins** [comment]
For quiet, the output should look something like this:

```
Cluster
#Nodes Configuration MinMemory CumulativeMemory
treeName1 MakespanAfterStep3 RuntimeOf3Steps
treeName2 MakespanAfterStep3 RuntimeOf3Steps
...

```

- Cluster output should appear once
- Configuration value will be filled out by me (it will be a new input parameter and then the cluster will be built differntly). treat it as an integer and maybe print always 0 for now
- MinMemory is the memory of the weakest node in cluster, can be acquired with getLastProcessor()
- Cumulative memory is sum of all memories of all nodes, is now being computed during build3LevelMemorySizes and buildHomogenenousMemorySizes, but can be pulled out of there in a separate method (maybe as a member function in the class Cluster, i.e. getCumulativeMemory() or smth similar)

**Comment by kulagins** [comment]
treeName is e.g. dump.Bova.123,nf; runtime is currently being computed by calling time() in the main method, it only needs to be printed

**Comment by paulhinzer** [comment]
there is no function `getLastProcessor()`, however, I have written one that does a linear search through the processor-list and then returns the one with the smalles Memory.
