### ISSUE TITLE
Cluster Configurator, Part 1

### ISSUE THREAD

**Issue by kulagins** [kulagins/tree-scheduler-refactored#23]
- Should enable describing a cluster in an external .txt (.xml, .json?) file, rather than hard-coding it in cluster.cpp.
- Should read the configuration from that file and create a corresponding cluster for each tree
- Static configuration remains the same
- Tree-dependent configuration means that the number of nodes is like in the config file, but the memory is tree-dependent
- The code decides how to treat the described cluster - as static or as tree-dependent. In the tree-dependent case the memory should be ignored and instead used the memory of the tree.
- The config file should be divided into groups, with the number of nodes, memory, and processor speed per group.

Example:

Number: 12
Memory: 12050
Speed: 1
Number: 20
Memory: 44560
Speed: 5
...

TODOS:

- See if there is an existing library for C++ that parses json or xml; but maybe it is easier to write by hand
- If so: for each line, parse the first word, if it is "Number", then start creating the next group of nodes.
- At the end, create the cluster, depending on the cluster_configuration parameter given to the code

**Comment by paulhinzer** [comment]
That works so far. If clustering mode is treeDependent, all the elements in the memories vector will get scaled by a fixed value (so far it was 10, for testing purposes)
